# Generated by Django 5.2.4 on 2025-12-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_note_genre_note_updated_at_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
